addr: ":8080"

clients:
  - name: "alice"
    token: "tok_alice_abc123"
    services:
      - id: "postgres"
        address: "postgres.app.svc.cluster.local:5432"
      - id: "redis"
        address: "redis.cache.svc.cluster.local:6379"

  - name: "bob"
    token: "tok_bob_xyz789"
    services:
      - id: "postgres"
        address: "postgres.app.svc.cluster.local:5432"
