services:
  tunn-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      TUNN_SERVER: "ws://host.docker.internal:8080/ws"
      TUNN_TOKEN: "tok_alice_abc123"
      TUNN_FORWARDS: "5432:postgres.app.svc.cluster.local:5432,6379:redis.cache.svc.cluster.local:6379"
    ports:
      - "5432:5432"
      - "6379:6379"
    restart: unless-stopped
