services:
  kunn-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      KUNN_SERVER: "ws://kunn-server.example.com/ws/client"
      KUNN_TOKEN: "tok_alice_abc123"
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
